### ISSUE TITLE
Uart processor drives Tx line hard blocking serial traffic

### ISSUE THREAD

**Issue by MRjimbob81** [slu4coder/Minimal-Terminal#6]
Not a bug per say - just an observation.

The UART/PS2 processor drives the Tx line constantly at such a level that it overpowers any other Tx data on that line.
An example would be where an upstream MCU receives serial input from the PS2 keyboard, PC serial output and/or output from another serial device.

Maybe making the Tx output hi-Z when not transmitting would allow other traffic to pass through.

**Comment by slu4coder** [comment]
Thanks for pointing this out. Since I am using the standard Arduino functions 'Serial.begin', 'Serial.print' etc. for this, I'd rather keep the code simple as it is. Feel free to experiment with fiddling around with the data direction register of the Arduino in between sending stuff to adapt for your needs.
